Update import statement for PluginPostStatusInfo
10up/insecure-content-warning pull request #178
Opened 2024-07-25 09:09 UTC by gabriel-glo

### Description of the Change

Update the import statement for `PluginPostStatusInfo` component to use unified extensibility API.

Closes #173

### How to test the Change

No functional changes to the plugin. 
Adding an image with HTTP source should trigger the notice in the sidebar when trying to save a post.

### Changelog Entry

> Changed - Changed import of `PluginPostStatusInfo` component from `@wordpress/edit-post` to `@wordpress/editor`

### Credits

Props @username, ...

### Checklist:

- [ ] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

2024-07-26 14:47 UTC, dkotter requested changes
So this works fine on WordPress 6.6 but our minimum here is still 6.4. Since the `@wordpress/editor` package doesn't contain the `PluginPostStatusInfo` component there, things break. So we'll either need to try loading from both locations or wait to make this change until 6.6 becomes our minimum

2024-07-26 15:23 UTC, gabriel-glo commented
If we decide with the implementation with both components, would the following approach be fine:

- Import  `PluginPostStatusInfo` from both `@wordpress/editor` and `@wordpress/edit-post` packages and rename them in the import. 
- Check either if WP version is higher than 6.6 or if component from `@wordpress/editor` is available and then render appropriate component with identical content.

2024-07-26 16:01 UTC, dkotter commented
> Import PluginPostStatusInfo from both @wordpress/editor and @wordpress/edit-post packages and rename them in the import.
> 
> Check either if WP version is higher than 6.6 or if component from @wordpress/editor is available and then render appropriate component with identical content.

I think this all sounds like a decent approach. May be able to simplify this and import first from the `@wordpress/editor` package and if `PluginPostStatusInfo` doesn't exist, then import from `@wordpress/edit-post`

2024-08-20 22:07 UTC, dkotter approved these changes

2024-08-20 22:13 UTC, merged