fix WP compat bump to version 6.6 in changelogs
10up/insecure-content-warning pull request #185
Opened 2024-08-26 22:04 UTC by jeffpaul

### Description of the Change
This PR updates the changelogs and update notices to state that the WP "tested up to" bumped to 6.6 and not 6.4.  I've already updated https://github.com/10up/insecure-content-warning/releases/tag/1.2.1 similarly.

### How to test the Change
Use GitHub markdown previewer to see changes.

### Changelog Entry

n/a

### Credits

Props @jeffpaul.

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [x] I have updated the documentation accordingly.
- [ ] I have added [Critical Flows, Test Cases, and/or End-to-End Tests](https://10up.github.io/Open-Source-Best-Practices/testing/) to cover my change.
- [ ] All new and existing tests pass.

2024-08-26 22:20 UTC, dkotter requested changes

2024-08-26 22:20 UTC, dkotter commented on CHANGELOG.md
> +**Note that this release bumps the WordPress minimum version from 5.8 to 6.6.**
So I don't think this is accurate, assuming I'm reading this correctly. We bumped the tested version to 6.6 but the minimum version is 6.4, which is what we call out here. So I think this should be left as-is

2024-08-27 13:58 UTC, jeffpaul commented on CHANGELOG.md
> +**Note that this release bumps the WordPress minimum version from 5.8 to 6.6.**
Bah, that's what I get for trying to clear through some tasks while sick in bed 🤦🏼

2024-08-27 14:51 UTC, dkotter approved these changes

2024-08-27 15:01 UTC, merged